#!/usr/bin/env python

import subprocess
import math
import datetime as dt
from typing import List, Tuple

digits = 4
delimiter = " "


def is_cwd_git_dir() -> bool:
    return (
        subprocess.run(
            ["git", "rev-parse", "--is-inside-work-tree"],
            capture_output=True,
        ).returncode
        == 0
    )


def ls_files() -> List[str]:
    return subprocess.run(
        ["git", "ls-files"], capture_output=True, text=True
    ).stdout.splitlines()


def lines(file: str) -> int:
    try:
        with open(file) as f:
            return sum(1 for _ in f)
    except:
        return -1


def ls_commit_dates(file: str) -> List[dt.date]:
    return [
        dt.date.fromisoformat(date.replace("'", ""))
        for date in subprocess.run(
            ["git", "log", "--format='%as'", "--", file], capture_output=True, text=True
        ).stdout.splitlines()
    ]


def normalize_timestamp(date: dt.date, first_date: dt.date, today: dt.date) -> float:
    total_days: int = (today - first_date).days
    days_from_first: int = (date - first_date).days
    return days_from_first / total_days if total_days != 0 else 1


def calc_hotspot_score(normalized_timestamps: List[float]) -> float:
    return sum(
        1 / (1 + math.e ** (-12 * normalized_timestamp + 12))
        for normalized_timestamp in normalized_timestamps
    )


def calc_hotspot_score_for_file(file: str, today: dt.date) -> float:
    dates = ls_commit_dates(file)
    first_date = dates[-1]
    normalized_timestamps = [
        normalize_timestamp(date, first_date, today) for date in dates
    ]
    return calc_hotspot_score(normalized_timestamps)


def normalize_score(score: float, min: float, max: float) -> float:
    return round((score - min) / (max - min), digits) if (max - min) != 0 else 1


def main():
    if not is_cwd_git_dir():
        return

    today: dt.date = dt.date.today()

    result: List[Tuple[float, int, str]] = [
        (calc_hotspot_score_for_file(file, today), lines(file), file)
        for file in ls_files()
    ]

    result = [(score, loc, file) for score, loc, file in result if loc > 0]

    result = [
        (
            normalize_score(
                score,
                min(score for score, _, _ in result),
                max(score for score, _, _ in result),
            ),
            loc,
            file,
        )
        for score, loc, file in result
    ]
    result.sort(key=lambda x: x[1], reverse=True)
    result.sort(key=lambda x: x[0], reverse=True)

    max_score_length = max(len(f"{score:.{digits}f}") for score, _, _ in result)
    max_loc_length = max(len(str(loc)) for _, loc, _ in result)
    print(
        delimiter.join(
            [f"{'score':>{max_score_length}}", f"{'loc':>{max_loc_length}}", "filename"]
        )
    )
    for score, loc, file in result:
        print(
            delimiter.join([f"{score:>.{digits}f}", f"{loc:>{max_loc_length}}", file])
        )


main()
